# coding: utf-8

"""
    nextcloud

    Nextcloud APIs  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.files_sharing_deleted_shareapi_api import FilesSharingDeletedShareapiApi  # noqa: E501
from openapi_client.rest import ApiException


class TestFilesSharingDeletedShareapiApi(unittest.TestCase):
    """FilesSharingDeletedShareapiApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.files_sharing_deleted_shareapi_api.FilesSharingDeletedShareapiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_files_sharing_deleted_shareapi_list(self):
        """Test case for files_sharing_deleted_shareapi_list

        Get a list of all deleted shares  # noqa: E501
        """
        pass

    def test_files_sharing_deleted_shareapi_undelete(self):
        """Test case for files_sharing_deleted_shareapi_undelete

        Undelete a deleted share  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
