# coding: utf-8

"""
    nextcloud

    Nextcloud APIs  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.dashboard_dashboard_api_get_widget_items200_response_ocs import DashboardDashboardApiGetWidgetItems200ResponseOcs  # noqa: E501
from openapi_client.rest import ApiException

class TestDashboardDashboardApiGetWidgetItems200ResponseOcs(unittest.TestCase):
    """DashboardDashboardApiGetWidgetItems200ResponseOcs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DashboardDashboardApiGetWidgetItems200ResponseOcs
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardDashboardApiGetWidgetItems200ResponseOcs`
        """
        model = openapi_client.models.dashboard_dashboard_api_get_widget_items200_response_ocs.DashboardDashboardApiGetWidgetItems200ResponseOcs()  # noqa: E501
        if include_optional :
            return DashboardDashboardApiGetWidgetItems200ResponseOcs(
                meta = openapi_client.models.ocs_meta.OCSMeta(
                    status = '', 
                    statuscode = 56, 
                    message = '', 
                    totalitems = '', 
                    itemsperpage = '', ), 
                data = {
                    'key' : [
                        openapi_client.models.dashboard_widget_item.DashboardWidgetItem(
                            subtitle = '', 
                            title = '', 
                            link = '', 
                            icon_url = '', 
                            since_id = '', )
                        ]
                    }
            )
        else :
            return DashboardDashboardApiGetWidgetItems200ResponseOcs(
                meta = openapi_client.models.ocs_meta.OCSMeta(
                    status = '', 
                    statuscode = 56, 
                    message = '', 
                    totalitems = '', 
                    itemsperpage = '', ),
                data = {
                    'key' : [
                        openapi_client.models.dashboard_widget_item.DashboardWidgetItem(
                            subtitle = '', 
                            title = '', 
                            link = '', 
                            icon_url = '', 
                            since_id = '', )
                        ]
                    },
        )
        """

    def testDashboardDashboardApiGetWidgetItems200ResponseOcs(self):
        """Test DashboardDashboardApiGetWidgetItems200ResponseOcs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
