# coding: utf-8

"""
    nextcloud

    Nextcloud APIs  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.core_hover_card_get_user200_response_ocs_data import CoreHoverCardGetUser200ResponseOcsData  # noqa: E501
from openapi_client.rest import ApiException

class TestCoreHoverCardGetUser200ResponseOcsData(unittest.TestCase):
    """CoreHoverCardGetUser200ResponseOcsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CoreHoverCardGetUser200ResponseOcsData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreHoverCardGetUser200ResponseOcsData`
        """
        model = openapi_client.models.core_hover_card_get_user200_response_ocs_data.CoreHoverCardGetUser200ResponseOcsData()  # noqa: E501
        if include_optional :
            return CoreHoverCardGetUser200ResponseOcsData(
                user_id = '', 
                display_name = '', 
                actions = [
                    openapi_client.models.core_contacts_action.CoreContactsAction(
                        title = '', 
                        icon = '', 
                        hyperlink = '', 
                        app_id = '', )
                    ]
            )
        else :
            return CoreHoverCardGetUser200ResponseOcsData(
                user_id = '',
                display_name = '',
                actions = [
                    openapi_client.models.core_contacts_action.CoreContactsAction(
                        title = '', 
                        icon = '', 
                        hyperlink = '', 
                        app_id = '', )
                    ],
        )
        """

    def testCoreHoverCardGetUser200ResponseOcsData(self):
        """Test CoreHoverCardGetUser200ResponseOcsData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
