# coding: utf-8

"""
    nextcloud

    Nextcloud APIs  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.core_translation_api_api import CoreTranslationApiApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCoreTranslationApiApi(unittest.TestCase):
    """CoreTranslationApiApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.core_translation_api_api.CoreTranslationApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_core_translation_api_languages(self):
        """Test case for core_translation_api_languages

        Get the list of supported languages  # noqa: E501
        """
        pass

    def test_core_translation_api_translate(self):
        """Test case for core_translation_api_translate

        Translate a text  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
