# coding: utf-8

"""
    nextcloud

    Nextcloud APIs  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.core_ocs_get_capabilities200_response_ocs_data_capabilities_files_sharing_public import CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic  # noqa: E501
from openapi_client.rest import ApiException

class TestCoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic(unittest.TestCase):
    """CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic`
        """
        model = openapi_client.models.core_ocs_get_capabilities200_response_ocs_data_capabilities_files_sharing_public.CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic()  # noqa: E501
        if include_optional :
            return CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic(
                enabled = True, 
                password = openapi_client.models.core_ocs_get_capabilities_200_response_ocs_data_capabilities_files_sharing_public_password.core_ocs_get_capabilities_200_response_ocs_data_capabilities_files_sharing_public_password(
                    enforced = True, 
                    ask_for_optional_password = True, ), 
                multiple_links = True, 
                expire_date = openapi_client.models.core_ocs_get_capabilities_200_response_ocs_data_capabilities_files_sharing_public_expire_date.core_ocs_get_capabilities_200_response_ocs_data_capabilities_files_sharing_public_expire_date(
                    enabled = True, 
                    days = 56, 
                    enforced = True, ), 
                expire_date_internal = openapi_client.models.core_ocs_get_capabilities_200_response_ocs_data_capabilities_files_sharing_public_expire_date.core_ocs_get_capabilities_200_response_ocs_data_capabilities_files_sharing_public_expire_date(
                    enabled = True, 
                    days = 56, 
                    enforced = True, ), 
                expire_date_remote = openapi_client.models.core_ocs_get_capabilities_200_response_ocs_data_capabilities_files_sharing_public_expire_date.core_ocs_get_capabilities_200_response_ocs_data_capabilities_files_sharing_public_expire_date(
                    enabled = True, 
                    days = 56, 
                    enforced = True, ), 
                send_mail = True, 
                upload = True, 
                upload_files_drop = True
            )
        else :
            return CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic(
                enabled = True,
        )
        """

    def testCoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic(self):
        """Test CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
