# coding: utf-8

"""
    nextcloud

    Nextcloud APIs  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.files_sharing_sharee_lookup_all_of_extra import FilesSharingShareeLookupAllOfExtra  # noqa: E501
from openapi_client.rest import ApiException

class TestFilesSharingShareeLookupAllOfExtra(unittest.TestCase):
    """FilesSharingShareeLookupAllOfExtra unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test FilesSharingShareeLookupAllOfExtra
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilesSharingShareeLookupAllOfExtra`
        """
        model = openapi_client.models.files_sharing_sharee_lookup_all_of_extra.FilesSharingShareeLookupAllOfExtra()  # noqa: E501
        if include_optional :
            return FilesSharingShareeLookupAllOfExtra(
                federation_id = '', 
                name = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ), 
                email = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ), 
                address = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ), 
                website = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ), 
                twitter = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ), 
                phone = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ), 
                twitter_signature = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ), 
                website_signature = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ), 
                userid = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, )
            )
        else :
            return FilesSharingShareeLookupAllOfExtra(
                federation_id = '',
                name = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
                email = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
                address = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
                website = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
                twitter = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
                phone = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
                twitter_signature = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
                website_signature = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
                userid = openapi_client.models.files_sharing_lookup.FilesSharingLookup(
                    value = '', 
                    verified = 56, ),
        )
        """

    def testFilesSharingShareeLookupAllOfExtra(self):
        """Test FilesSharingShareeLookupAllOfExtra"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
