/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DashboardDashboardApiGetWidgetItemsV2200ResponseOcs {
    #[serde(rename = "meta")]
    pub meta: Box<crate::models::OcsMeta>,
    #[serde(rename = "data")]
    pub data: ::std::collections::HashMap<String, crate::models::DashboardWidgetItems>,
}

impl DashboardDashboardApiGetWidgetItemsV2200ResponseOcs {
    pub fn new(meta: crate::models::OcsMeta, data: ::std::collections::HashMap<String, crate::models::DashboardWidgetItems>) -> DashboardDashboardApiGetWidgetItemsV2200ResponseOcs {
        DashboardDashboardApiGetWidgetItemsV2200ResponseOcs {
            meta: Box::new(meta),
            data,
        }
    }
}


