/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DavDirectGetUrl200ResponseOcsData {
    #[serde(rename = "url")]
    pub url: String,
}

impl DavDirectGetUrl200ResponseOcsData {
    pub fn new(url: String) -> DavDirectGetUrl200ResponseOcsData {
        DavDirectGetUrl200ResponseOcsData {
            url,
        }
    }
}


