/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesSharingCapabilities {
    #[serde(rename = "files_sharing")]
    pub files_sharing: Box<crate::models::FilesSharingCapabilitiesFilesSharing>,
}

impl FilesSharingCapabilities {
    pub fn new(files_sharing: crate::models::FilesSharingCapabilitiesFilesSharing) -> FilesSharingCapabilities {
        FilesSharingCapabilities {
            files_sharing: Box::new(files_sharing),
        }
    }
}


