/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesDirectEditingInfo200ResponseOcsData {
    #[serde(rename = "editors")]
    pub editors: ::std::collections::HashMap<String, crate::models::FilesDirectEditingInfo200ResponseOcsDataEditorsValue>,
    #[serde(rename = "creators")]
    pub creators: ::std::collections::HashMap<String, crate::models::FilesDirectEditingInfo200ResponseOcsDataCreatorsValue>,
}

impl FilesDirectEditingInfo200ResponseOcsData {
    pub fn new(editors: ::std::collections::HashMap<String, crate::models::FilesDirectEditingInfo200ResponseOcsDataEditorsValue>, creators: ::std::collections::HashMap<String, crate::models::FilesDirectEditingInfo200ResponseOcsDataCreatorsValue>) -> FilesDirectEditingInfo200ResponseOcsData {
        FilesDirectEditingInfo200ResponseOcsData {
            editors,
            creators,
        }
    }
}


