/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesVersionsCapabilities {
    #[serde(rename = "files")]
    pub files: Box<crate::models::FilesVersionsCapabilitiesFiles>,
}

impl FilesVersionsCapabilities {
    pub fn new(files: crate::models::FilesVersionsCapabilitiesFiles) -> FilesVersionsCapabilities {
        FilesVersionsCapabilities {
            files: Box::new(files),
        }
    }
}


