/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesTrashbinCapabilities {
    #[serde(rename = "files")]
    pub files: Box<crate::models::FilesTrashbinCapabilitiesFiles>,
}

impl FilesTrashbinCapabilities {
    pub fn new(files: crate::models::FilesTrashbinCapabilitiesFiles) -> FilesTrashbinCapabilities {
        FilesTrashbinCapabilities {
            files: Box::new(files),
        }
    }
}


