/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilesCapabilitiesFilesDirectEditing {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "etag")]
    pub etag: String,
    #[serde(rename = "supportsFileId")]
    pub supports_file_id: bool,
}

impl FilesCapabilitiesFilesDirectEditing {
    pub fn new(url: String, etag: String, supports_file_id: bool) -> FilesCapabilitiesFilesDirectEditing {
        FilesCapabilitiesFilesDirectEditing {
            url,
            etag,
            supports_file_id,
        }
    }
}


