# coding: utf-8

"""
    nextcloud

    Nextcloud APIs  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, validator
from openapi_client.models.user_status_clear_at_time import UserStatusClearAtTime

class UserStatusClearAt(BaseModel):
    """
    UserStatusClearAt
    """
    type: StrictStr = Field(...)
    time: UserStatusClearAtTime = Field(...)
    __properties = ["type", "time"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('period', 'end-of'):
            raise ValueError("must be one of enum values ('period', 'end-of')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UserStatusClearAt:
        """Create an instance of UserStatusClearAt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of time
        if self.time:
            _dict['time'] = self.time.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UserStatusClearAt:
        """Create an instance of UserStatusClearAt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UserStatusClearAt.parse_obj(obj)

        _obj = UserStatusClearAt.parse_obj({
            "type": obj.get("type"),
            "time": UserStatusClearAtTime.from_dict(obj.get("time")) if obj.get("time") is not None else None
        })
        return _obj

