/*
nextcloud

Nextcloud APIs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_sdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
	"os"
)


type ThemingThemingAPI interface {

	/*
	ThemingThemingGetImage Get an image

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param key Key of the image
	@return ThemingThemingAPIThemingThemingGetImageRequest
	*/
	ThemingThemingGetImage(ctx context.Context, key string) ThemingThemingAPIThemingThemingGetImageRequest

	// ThemingThemingGetImageExecute executes the request
	//  @return *os.File
	ThemingThemingGetImageExecute(r ThemingThemingAPIThemingThemingGetImageRequest) (*os.File, *http.Response, error)

	/*
	ThemingThemingGetManifest Get the manifest for an app

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param app ID of the app
	@return ThemingThemingAPIThemingThemingGetManifestRequest
	*/
	ThemingThemingGetManifest(ctx context.Context, app string) ThemingThemingAPIThemingThemingGetManifestRequest

	// ThemingThemingGetManifestExecute executes the request
	//  @return ThemingThemingGetManifest200Response
	ThemingThemingGetManifestExecute(r ThemingThemingAPIThemingThemingGetManifestRequest) (*ThemingThemingGetManifest200Response, *http.Response, error)

	/*
	ThemingThemingGetThemeStylesheet Get the CSS stylesheet for a theme

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param themeId ID of the theme
	@return ThemingThemingAPIThemingThemingGetThemeStylesheetRequest
	*/
	ThemingThemingGetThemeStylesheet(ctx context.Context, themeId string) ThemingThemingAPIThemingThemingGetThemeStylesheetRequest

	// ThemingThemingGetThemeStylesheetExecute executes the request
	//  @return *os.File
	ThemingThemingGetThemeStylesheetExecute(r ThemingThemingAPIThemingThemingGetThemeStylesheetRequest) (*os.File, *http.Response, error)
}

// ThemingThemingAPIService ThemingThemingAPI service
type ThemingThemingAPIService service

type ThemingThemingAPIThemingThemingGetImageRequest struct {
	ctx context.Context
	ApiService ThemingThemingAPI
	key string
	useSvg *int32
}

// Return image as SVG
func (r ThemingThemingAPIThemingThemingGetImageRequest) UseSvg(useSvg int32) ThemingThemingAPIThemingThemingGetImageRequest {
	r.useSvg = &useSvg
	return r
}

func (r ThemingThemingAPIThemingThemingGetImageRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.ThemingThemingGetImageExecute(r)
}

/*
ThemingThemingGetImage Get an image

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param key Key of the image
 @return ThemingThemingAPIThemingThemingGetImageRequest
*/
func (a *ThemingThemingAPIService) ThemingThemingGetImage(ctx context.Context, key string) ThemingThemingAPIThemingThemingGetImageRequest {
	return ThemingThemingAPIThemingThemingGetImageRequest{
		ApiService: a,
		ctx: ctx,
		key: key,
	}
}

// Execute executes the request
//  @return *os.File
func (a *ThemingThemingAPIService) ThemingThemingGetImageExecute(r ThemingThemingAPIThemingThemingGetImageRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ThemingThemingAPIService.ThemingThemingGetImage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/index.php/apps/theming/image/{key}"
	localVarPath = strings.Replace(localVarPath, "{"+"key"+"}", url.PathEscape(parameterValueToString(r.key, "key")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.useSvg != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "useSvg", r.useSvg, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ThemingThemingAPIThemingThemingGetManifestRequest struct {
	ctx context.Context
	ApiService ThemingThemingAPI
	app string
}

func (r ThemingThemingAPIThemingThemingGetManifestRequest) Execute() (*ThemingThemingGetManifest200Response, *http.Response, error) {
	return r.ApiService.ThemingThemingGetManifestExecute(r)
}

/*
ThemingThemingGetManifest Get the manifest for an app

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param app ID of the app
 @return ThemingThemingAPIThemingThemingGetManifestRequest
*/
func (a *ThemingThemingAPIService) ThemingThemingGetManifest(ctx context.Context, app string) ThemingThemingAPIThemingThemingGetManifestRequest {
	return ThemingThemingAPIThemingThemingGetManifestRequest{
		ApiService: a,
		ctx: ctx,
		app: app,
	}
}

// Execute executes the request
//  @return ThemingThemingGetManifest200Response
func (a *ThemingThemingAPIService) ThemingThemingGetManifestExecute(r ThemingThemingAPIThemingThemingGetManifestRequest) (*ThemingThemingGetManifest200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ThemingThemingGetManifest200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ThemingThemingAPIService.ThemingThemingGetManifest")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/index.php/apps/theming/manifest/{app}"
	localVarPath = strings.Replace(localVarPath, "{"+"app"+"}", url.PathEscape(parameterValueToString(r.app, "app")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ThemingThemingAPIThemingThemingGetThemeStylesheetRequest struct {
	ctx context.Context
	ApiService ThemingThemingAPI
	themeId string
	plain *int32
	withCustomCss *int32
}

// Let the browser decide the CSS priority
func (r ThemingThemingAPIThemingThemingGetThemeStylesheetRequest) Plain(plain int32) ThemingThemingAPIThemingThemingGetThemeStylesheetRequest {
	r.plain = &plain
	return r
}

// Include custom CSS
func (r ThemingThemingAPIThemingThemingGetThemeStylesheetRequest) WithCustomCss(withCustomCss int32) ThemingThemingAPIThemingThemingGetThemeStylesheetRequest {
	r.withCustomCss = &withCustomCss
	return r
}

func (r ThemingThemingAPIThemingThemingGetThemeStylesheetRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.ThemingThemingGetThemeStylesheetExecute(r)
}

/*
ThemingThemingGetThemeStylesheet Get the CSS stylesheet for a theme

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param themeId ID of the theme
 @return ThemingThemingAPIThemingThemingGetThemeStylesheetRequest
*/
func (a *ThemingThemingAPIService) ThemingThemingGetThemeStylesheet(ctx context.Context, themeId string) ThemingThemingAPIThemingThemingGetThemeStylesheetRequest {
	return ThemingThemingAPIThemingThemingGetThemeStylesheetRequest{
		ApiService: a,
		ctx: ctx,
		themeId: themeId,
	}
}

// Execute executes the request
//  @return *os.File
func (a *ThemingThemingAPIService) ThemingThemingGetThemeStylesheetExecute(r ThemingThemingAPIThemingThemingGetThemeStylesheetRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ThemingThemingAPIService.ThemingThemingGetThemeStylesheet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/index.php/apps/theming/theme/{themeId}.css"
	localVarPath = strings.Replace(localVarPath, "{"+"themeId"+"}", url.PathEscape(parameterValueToString(r.themeId, "themeId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.plain != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "plain", r.plain, "")
	}
	if r.withCustomCss != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "withCustomCss", r.withCustomCss, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/css"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
