/*
nextcloud

Nextcloud APIs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_sdk

import (
	"encoding/json"
)

// checks if the FilesDirectEditingInfo200ResponseOcsDataCreatorsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesDirectEditingInfo200ResponseOcsDataCreatorsValue{}

// FilesDirectEditingInfo200ResponseOcsDataCreatorsValue struct for FilesDirectEditingInfo200ResponseOcsDataCreatorsValue
type FilesDirectEditingInfo200ResponseOcsDataCreatorsValue struct {
	Id string `json:"id"`
	Editor string `json:"editor"`
	Name string `json:"name"`
	Extension string `json:"extension"`
	Templates bool `json:"templates"`
	Mimetypes []string `json:"mimetypes"`
	AdditionalProperties map[string]interface{}
}

type _FilesDirectEditingInfo200ResponseOcsDataCreatorsValue FilesDirectEditingInfo200ResponseOcsDataCreatorsValue

// NewFilesDirectEditingInfo200ResponseOcsDataCreatorsValue instantiates a new FilesDirectEditingInfo200ResponseOcsDataCreatorsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesDirectEditingInfo200ResponseOcsDataCreatorsValue(id string, editor string, name string, extension string, templates bool, mimetypes []string) *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue {
	this := FilesDirectEditingInfo200ResponseOcsDataCreatorsValue{}
	this.Id = id
	this.Editor = editor
	this.Name = name
	this.Extension = extension
	this.Templates = templates
	this.Mimetypes = mimetypes
	return &this
}

// NewFilesDirectEditingInfo200ResponseOcsDataCreatorsValueWithDefaults instantiates a new FilesDirectEditingInfo200ResponseOcsDataCreatorsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesDirectEditingInfo200ResponseOcsDataCreatorsValueWithDefaults() *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue {
	this := FilesDirectEditingInfo200ResponseOcsDataCreatorsValue{}
	return &this
}

// GetId returns the Id field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) SetId(v string) {
	o.Id = v
}

// GetEditor returns the Editor field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetEditor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Editor
}

// GetEditorOk returns a tuple with the Editor field value
// and a boolean to check if the value has been set.
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetEditorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Editor, true
}

// SetEditor sets field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) SetEditor(v string) {
	o.Editor = v
}

// GetName returns the Name field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) SetName(v string) {
	o.Name = v
}

// GetExtension returns the Extension field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetExtension() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Extension
}

// GetExtensionOk returns a tuple with the Extension field value
// and a boolean to check if the value has been set.
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetExtensionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Extension, true
}

// SetExtension sets field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) SetExtension(v string) {
	o.Extension = v
}

// GetTemplates returns the Templates field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetTemplates() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Templates
}

// GetTemplatesOk returns a tuple with the Templates field value
// and a boolean to check if the value has been set.
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetTemplatesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Templates, true
}

// SetTemplates sets field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) SetTemplates(v bool) {
	o.Templates = v
}

// GetMimetypes returns the Mimetypes field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetMimetypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Mimetypes
}

// GetMimetypesOk returns a tuple with the Mimetypes field value
// and a boolean to check if the value has been set.
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) GetMimetypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mimetypes, true
}

// SetMimetypes sets field value
func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) SetMimetypes(v []string) {
	o.Mimetypes = v
}

func (o FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["editor"] = o.Editor
	toSerialize["name"] = o.Name
	toSerialize["extension"] = o.Extension
	toSerialize["templates"] = o.Templates
	toSerialize["mimetypes"] = o.Mimetypes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) UnmarshalJSON(bytes []byte) (err error) {
	varFilesDirectEditingInfo200ResponseOcsDataCreatorsValue := _FilesDirectEditingInfo200ResponseOcsDataCreatorsValue{}

	if err = json.Unmarshal(bytes, &varFilesDirectEditingInfo200ResponseOcsDataCreatorsValue); err == nil {
		*o = FilesDirectEditingInfo200ResponseOcsDataCreatorsValue(varFilesDirectEditingInfo200ResponseOcsDataCreatorsValue)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "editor")
		delete(additionalProperties, "name")
		delete(additionalProperties, "extension")
		delete(additionalProperties, "templates")
		delete(additionalProperties, "mimetypes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue struct {
	value *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue
	isSet bool
}

func (v NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue) Get() *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue {
	return v.value
}

func (v *NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue) Set(val *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue(val *FilesDirectEditingInfo200ResponseOcsDataCreatorsValue) *NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue {
	return &NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue{value: val, isSet: true}
}

func (v NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesDirectEditingInfo200ResponseOcsDataCreatorsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


