/*
nextcloud

Nextcloud APIs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_sdk

import (
	"encoding/json"
)

// checks if the FilesExternalApiGetUserMounts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesExternalApiGetUserMounts200Response{}

// FilesExternalApiGetUserMounts200Response struct for FilesExternalApiGetUserMounts200Response
type FilesExternalApiGetUserMounts200Response struct {
	Ocs FilesExternalApiGetUserMounts200ResponseOcs `json:"ocs"`
	AdditionalProperties map[string]interface{}
}

type _FilesExternalApiGetUserMounts200Response FilesExternalApiGetUserMounts200Response

// NewFilesExternalApiGetUserMounts200Response instantiates a new FilesExternalApiGetUserMounts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesExternalApiGetUserMounts200Response(ocs FilesExternalApiGetUserMounts200ResponseOcs) *FilesExternalApiGetUserMounts200Response {
	this := FilesExternalApiGetUserMounts200Response{}
	this.Ocs = ocs
	return &this
}

// NewFilesExternalApiGetUserMounts200ResponseWithDefaults instantiates a new FilesExternalApiGetUserMounts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesExternalApiGetUserMounts200ResponseWithDefaults() *FilesExternalApiGetUserMounts200Response {
	this := FilesExternalApiGetUserMounts200Response{}
	return &this
}

// GetOcs returns the Ocs field value
func (o *FilesExternalApiGetUserMounts200Response) GetOcs() FilesExternalApiGetUserMounts200ResponseOcs {
	if o == nil {
		var ret FilesExternalApiGetUserMounts200ResponseOcs
		return ret
	}

	return o.Ocs
}

// GetOcsOk returns a tuple with the Ocs field value
// and a boolean to check if the value has been set.
func (o *FilesExternalApiGetUserMounts200Response) GetOcsOk() (*FilesExternalApiGetUserMounts200ResponseOcs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ocs, true
}

// SetOcs sets field value
func (o *FilesExternalApiGetUserMounts200Response) SetOcs(v FilesExternalApiGetUserMounts200ResponseOcs) {
	o.Ocs = v
}

func (o FilesExternalApiGetUserMounts200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesExternalApiGetUserMounts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ocs"] = o.Ocs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FilesExternalApiGetUserMounts200Response) UnmarshalJSON(bytes []byte) (err error) {
	varFilesExternalApiGetUserMounts200Response := _FilesExternalApiGetUserMounts200Response{}

	if err = json.Unmarshal(bytes, &varFilesExternalApiGetUserMounts200Response); err == nil {
		*o = FilesExternalApiGetUserMounts200Response(varFilesExternalApiGetUserMounts200Response)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "ocs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFilesExternalApiGetUserMounts200Response struct {
	value *FilesExternalApiGetUserMounts200Response
	isSet bool
}

func (v NullableFilesExternalApiGetUserMounts200Response) Get() *FilesExternalApiGetUserMounts200Response {
	return v.value
}

func (v *NullableFilesExternalApiGetUserMounts200Response) Set(val *FilesExternalApiGetUserMounts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesExternalApiGetUserMounts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesExternalApiGetUserMounts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesExternalApiGetUserMounts200Response(val *FilesExternalApiGetUserMounts200Response) *NullableFilesExternalApiGetUserMounts200Response {
	return &NullableFilesExternalApiGetUserMounts200Response{value: val, isSet: true}
}

func (v NullableFilesExternalApiGetUserMounts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesExternalApiGetUserMounts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


