/*
nextcloud

Nextcloud APIs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client_sdk

import (
	"encoding/json"
)

// checks if the DashboardDashboardApiGetWidgetItemsV2200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardDashboardApiGetWidgetItemsV2200Response{}

// DashboardDashboardApiGetWidgetItemsV2200Response struct for DashboardDashboardApiGetWidgetItemsV2200Response
type DashboardDashboardApiGetWidgetItemsV2200Response struct {
	Ocs DashboardDashboardApiGetWidgetItemsV2200ResponseOcs `json:"ocs"`
	AdditionalProperties map[string]interface{}
}

type _DashboardDashboardApiGetWidgetItemsV2200Response DashboardDashboardApiGetWidgetItemsV2200Response

// NewDashboardDashboardApiGetWidgetItemsV2200Response instantiates a new DashboardDashboardApiGetWidgetItemsV2200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardDashboardApiGetWidgetItemsV2200Response(ocs DashboardDashboardApiGetWidgetItemsV2200ResponseOcs) *DashboardDashboardApiGetWidgetItemsV2200Response {
	this := DashboardDashboardApiGetWidgetItemsV2200Response{}
	this.Ocs = ocs
	return &this
}

// NewDashboardDashboardApiGetWidgetItemsV2200ResponseWithDefaults instantiates a new DashboardDashboardApiGetWidgetItemsV2200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardDashboardApiGetWidgetItemsV2200ResponseWithDefaults() *DashboardDashboardApiGetWidgetItemsV2200Response {
	this := DashboardDashboardApiGetWidgetItemsV2200Response{}
	return &this
}

// GetOcs returns the Ocs field value
func (o *DashboardDashboardApiGetWidgetItemsV2200Response) GetOcs() DashboardDashboardApiGetWidgetItemsV2200ResponseOcs {
	if o == nil {
		var ret DashboardDashboardApiGetWidgetItemsV2200ResponseOcs
		return ret
	}

	return o.Ocs
}

// GetOcsOk returns a tuple with the Ocs field value
// and a boolean to check if the value has been set.
func (o *DashboardDashboardApiGetWidgetItemsV2200Response) GetOcsOk() (*DashboardDashboardApiGetWidgetItemsV2200ResponseOcs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ocs, true
}

// SetOcs sets field value
func (o *DashboardDashboardApiGetWidgetItemsV2200Response) SetOcs(v DashboardDashboardApiGetWidgetItemsV2200ResponseOcs) {
	o.Ocs = v
}

func (o DashboardDashboardApiGetWidgetItemsV2200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardDashboardApiGetWidgetItemsV2200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ocs"] = o.Ocs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DashboardDashboardApiGetWidgetItemsV2200Response) UnmarshalJSON(bytes []byte) (err error) {
	varDashboardDashboardApiGetWidgetItemsV2200Response := _DashboardDashboardApiGetWidgetItemsV2200Response{}

	if err = json.Unmarshal(bytes, &varDashboardDashboardApiGetWidgetItemsV2200Response); err == nil {
		*o = DashboardDashboardApiGetWidgetItemsV2200Response(varDashboardDashboardApiGetWidgetItemsV2200Response)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "ocs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDashboardDashboardApiGetWidgetItemsV2200Response struct {
	value *DashboardDashboardApiGetWidgetItemsV2200Response
	isSet bool
}

func (v NullableDashboardDashboardApiGetWidgetItemsV2200Response) Get() *DashboardDashboardApiGetWidgetItemsV2200Response {
	return v.value
}

func (v *NullableDashboardDashboardApiGetWidgetItemsV2200Response) Set(val *DashboardDashboardApiGetWidgetItemsV2200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardDashboardApiGetWidgetItemsV2200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardDashboardApiGetWidgetItemsV2200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardDashboardApiGetWidgetItemsV2200Response(val *DashboardDashboardApiGetWidgetItemsV2200Response) *NullableDashboardDashboardApiGetWidgetItemsV2200Response {
	return &NullableDashboardDashboardApiGetWidgetItemsV2200Response{value: val, isSet: true}
}

func (v NullableDashboardDashboardApiGetWidgetItemsV2200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardDashboardApiGetWidgetItemsV2200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


