/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudFederationApiValidationErrorAllOf {
    #[serde(rename = "validationErrors")]
    pub validation_errors: Vec<crate::models::CloudFederationApiValidationErrorAllOfValidationErrors>,
}

impl CloudFederationApiValidationErrorAllOf {
    pub fn new(validation_errors: Vec<crate::models::CloudFederationApiValidationErrorAllOfValidationErrors>) -> CloudFederationApiValidationErrorAllOf {
        CloudFederationApiValidationErrorAllOf {
            validation_errors,
        }
    }
}


