/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<Box<crate::models::CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublicPassword>>,
    #[serde(rename = "multiple_links", skip_serializing_if = "Option::is_none")]
    pub multiple_links: Option<bool>,
    #[serde(rename = "expire_date", skip_serializing_if = "Option::is_none")]
    pub expire_date: Option<Box<crate::models::CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublicExpireDate>>,
    #[serde(rename = "expire_date_internal", skip_serializing_if = "Option::is_none")]
    pub expire_date_internal: Option<Box<crate::models::CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublicExpireDate>>,
    #[serde(rename = "expire_date_remote", skip_serializing_if = "Option::is_none")]
    pub expire_date_remote: Option<Box<crate::models::CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublicExpireDate>>,
    #[serde(rename = "send_mail", skip_serializing_if = "Option::is_none")]
    pub send_mail: Option<bool>,
    #[serde(rename = "upload", skip_serializing_if = "Option::is_none")]
    pub upload: Option<bool>,
    #[serde(rename = "upload_files_drop", skip_serializing_if = "Option::is_none")]
    pub upload_files_drop: Option<bool>,
}

impl CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic {
    pub fn new(enabled: bool) -> CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic {
        CoreOcsGetCapabilities200ResponseOcsDataCapabilitiesFilesSharingPublic {
            enabled,
            password: None,
            multiple_links: None,
            expire_date: None,
            expire_date_internal: None,
            expire_date_remote: None,
            send_mail: None,
            upload: None,
            upload_files_drop: None,
        }
    }
}


