/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FilesSharingShareeRemoteAllOfValue {
    #[serde(rename = "shareType")]
    pub share_type: i64,
    #[serde(rename = "shareWith")]
    pub share_with: String,
    #[serde(rename = "server")]
    pub server: String,
}

impl FilesSharingShareeRemoteAllOfValue {
    pub fn new(share_type: i64, share_with: String, server: String) -> FilesSharingShareeRemoteAllOfValue {
        FilesSharingShareeRemoteAllOfValue {
            share_type,
            share_with,
            server,
        }
    }
}


