/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FilesSharingShareeCircleAllOf {
    #[serde(rename = "shareWithDescription")]
    pub share_with_description: String,
    #[serde(rename = "value")]
    pub value: Box<crate::models::FilesSharingShareeCircleAllOfValue>,
}

impl FilesSharingShareeCircleAllOf {
    pub fn new(share_with_description: String, value: crate::models::FilesSharingShareeCircleAllOfValue) -> FilesSharingShareeCircleAllOf {
        FilesSharingShareeCircleAllOf {
            share_with_description,
            value: Box::new(value),
        }
    }
}


