/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FilesSharingShareStatusOneOf {
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<String>,
    #[serde(rename = "icon", deserialize_with = "Option::deserialize")]
    pub icon: Option<String>,
    #[serde(rename = "clearAt", deserialize_with = "Option::deserialize")]
    pub clear_at: Option<i64>,
}

impl FilesSharingShareStatusOneOf {
    pub fn new(status: String, message: Option<String>, icon: Option<String>, clear_at: Option<i64>) -> FilesSharingShareStatusOneOf {
        FilesSharingShareStatusOneOf {
            status,
            message,
            icon,
            clear_at,
        }
    }
}


