/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FilesSharingShareeLookupAllOfValue {
    #[serde(rename = "shareType")]
    pub share_type: i64,
    #[serde(rename = "shareWith")]
    pub share_with: String,
    #[serde(rename = "globalScale")]
    pub global_scale: bool,
}

impl FilesSharingShareeLookupAllOfValue {
    pub fn new(share_type: i64, share_with: String, global_scale: bool) -> FilesSharingShareeLookupAllOfValue {
        FilesSharingShareeLookupAllOfValue {
            share_type,
            share_with,
            global_scale,
        }
    }
}


