/*
 * nextcloud
 *
 * Nextcloud APIs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProvisioningApiGroupsGetGroupUsersDetails200ResponseOcsData {
    #[serde(rename = "users")]
    pub users: ::std::collections::HashMap<String, crate::models::ProvisioningApiGroupsGetGroupUsersDetails200ResponseOcsDataUsersValue>,
}

impl ProvisioningApiGroupsGetGroupUsersDetails200ResponseOcsData {
    pub fn new(users: ::std::collections::HashMap<String, crate::models::ProvisioningApiGroupsGetGroupUsersDetails200ResponseOcsDataUsersValue>) -> ProvisioningApiGroupsGetGroupUsersDetails200ResponseOcsData {
        ProvisioningApiGroupsGetGroupUsersDetails200ResponseOcsData {
            users,
        }
    }
}


