/*
nextcloud

Nextcloud APIs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FilesSharingRemoteGetShares200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesSharingRemoteGetShares200Response{}

// FilesSharingRemoteGetShares200Response struct for FilesSharingRemoteGetShares200Response
type FilesSharingRemoteGetShares200Response struct {
	Ocs FilesSharingRemoteGetShares200ResponseOcs `json:"ocs"`
}

// NewFilesSharingRemoteGetShares200Response instantiates a new FilesSharingRemoteGetShares200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesSharingRemoteGetShares200Response(ocs FilesSharingRemoteGetShares200ResponseOcs) *FilesSharingRemoteGetShares200Response {
	this := FilesSharingRemoteGetShares200Response{}
	this.Ocs = ocs
	return &this
}

// NewFilesSharingRemoteGetShares200ResponseWithDefaults instantiates a new FilesSharingRemoteGetShares200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesSharingRemoteGetShares200ResponseWithDefaults() *FilesSharingRemoteGetShares200Response {
	this := FilesSharingRemoteGetShares200Response{}
	return &this
}

// GetOcs returns the Ocs field value
func (o *FilesSharingRemoteGetShares200Response) GetOcs() FilesSharingRemoteGetShares200ResponseOcs {
	if o == nil {
		var ret FilesSharingRemoteGetShares200ResponseOcs
		return ret
	}

	return o.Ocs
}

// GetOcsOk returns a tuple with the Ocs field value
// and a boolean to check if the value has been set.
func (o *FilesSharingRemoteGetShares200Response) GetOcsOk() (*FilesSharingRemoteGetShares200ResponseOcs, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ocs, true
}

// SetOcs sets field value
func (o *FilesSharingRemoteGetShares200Response) SetOcs(v FilesSharingRemoteGetShares200ResponseOcs) {
	o.Ocs = v
}

func (o FilesSharingRemoteGetShares200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesSharingRemoteGetShares200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ocs"] = o.Ocs
	return toSerialize, nil
}

type NullableFilesSharingRemoteGetShares200Response struct {
	value *FilesSharingRemoteGetShares200Response
	isSet bool
}

func (v NullableFilesSharingRemoteGetShares200Response) Get() *FilesSharingRemoteGetShares200Response {
	return v.value
}

func (v *NullableFilesSharingRemoteGetShares200Response) Set(val *FilesSharingRemoteGetShares200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesSharingRemoteGetShares200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesSharingRemoteGetShares200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesSharingRemoteGetShares200Response(val *FilesSharingRemoteGetShares200Response) *NullableFilesSharingRemoteGetShares200Response {
	return &NullableFilesSharingRemoteGetShares200Response{value: val, isSet: true}
}

func (v NullableFilesSharingRemoteGetShares200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesSharingRemoteGetShares200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


