/*
nextcloud

Nextcloud APIs

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FilesSharingSharee type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilesSharingSharee{}

// FilesSharingSharee struct for FilesSharingSharee
type FilesSharingSharee struct {
	Count NullableInt64 `json:"count"`
	Label string `json:"label"`
}

// NewFilesSharingSharee instantiates a new FilesSharingSharee object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilesSharingSharee(count NullableInt64, label string) *FilesSharingSharee {
	this := FilesSharingSharee{}
	this.Count = count
	this.Label = label
	return &this
}

// NewFilesSharingShareeWithDefaults instantiates a new FilesSharingSharee object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilesSharingShareeWithDefaults() *FilesSharingSharee {
	this := FilesSharingSharee{}
	return &this
}

// GetCount returns the Count field value
// If the value is explicit nil, the zero value for int64 will be returned
func (o *FilesSharingSharee) GetCount() int64 {
	if o == nil || o.Count.Get() == nil {
		var ret int64
		return ret
	}

	return *o.Count.Get()
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FilesSharingSharee) GetCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Count.Get(), o.Count.IsSet()
}

// SetCount sets field value
func (o *FilesSharingSharee) SetCount(v int64) {
	o.Count.Set(&v)
}

// GetLabel returns the Label field value
func (o *FilesSharingSharee) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *FilesSharingSharee) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *FilesSharingSharee) SetLabel(v string) {
	o.Label = v
}

func (o FilesSharingSharee) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilesSharingSharee) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count.Get()
	toSerialize["label"] = o.Label
	return toSerialize, nil
}

type NullableFilesSharingSharee struct {
	value *FilesSharingSharee
	isSet bool
}

func (v NullableFilesSharingSharee) Get() *FilesSharingSharee {
	return v.value
}

func (v *NullableFilesSharingSharee) Set(val *FilesSharingSharee) {
	v.value = val
	v.isSet = true
}

func (v NullableFilesSharingSharee) IsSet() bool {
	return v.isSet
}

func (v *NullableFilesSharingSharee) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilesSharingSharee(val *FilesSharingSharee) *NullableFilesSharingSharee {
	return &NullableFilesSharingSharee{value: val, isSet: true}
}

func (v NullableFilesSharingSharee) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilesSharingSharee) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


