# flake8: noqa

# import apis into api package
from openapi_client.api.cloud_federation_api_request_handler_api import CloudFederationApiRequestHandlerApi
from openapi_client.api.core_api import CoreApi
from openapi_client.api.core_app_password_api import CoreAppPasswordApi
from openapi_client.api.core_auto_complete_api import CoreAutoCompleteApi
from openapi_client.api.core_avatar_api import CoreAvatarApi
from openapi_client.api.core_client_flow_login_v2_api import CoreClientFlowLoginV2Api
from openapi_client.api.core_collaboration_resources_api import CoreCollaborationResourcesApi
from openapi_client.api.core_guest_avatar_api import CoreGuestAvatarApi
from openapi_client.api.core_hover_card_api import CoreHoverCardApi
from openapi_client.api.core_navigation_api import CoreNavigationApi
from openapi_client.api.core_ocs_api import CoreOcsApi
from openapi_client.api.core_preview_api import CorePreviewApi
from openapi_client.api.core_profile_api_api import CoreProfileApiApi
from openapi_client.api.core_reference_api import CoreReferenceApi
from openapi_client.api.core_reference_api_api import CoreReferenceApiApi
from openapi_client.api.core_translation_api_api import CoreTranslationApiApi
from openapi_client.api.core_unified_search_api import CoreUnifiedSearchApi
from openapi_client.api.core_whats_new_api import CoreWhatsNewApi
from openapi_client.api.core_wipe_api import CoreWipeApi
from openapi_client.api.dashboard_dashboard_api_api import DashboardDashboardApiApi
from openapi_client.api.dav_direct_api import DavDirectApi
from openapi_client.api.files_sharing_deleted_shareapi_api import FilesSharingDeletedShareapiApi
from openapi_client.api.files_sharing_remote_api import FilesSharingRemoteApi
from openapi_client.api.files_sharing_share_info_api import FilesSharingShareInfoApi
from openapi_client.api.files_sharing_shareapi_api import FilesSharingShareapiApi
from openapi_client.api.files_sharing_shareesapi_api import FilesSharingShareesapiApi
from openapi_client.api.oauth2_login_redirector_api import Oauth2LoginRedirectorApi
from openapi_client.api.oauth2_oauth_api_api import Oauth2OauthApiApi
from openapi_client.api.provisioning_api_app_config_api import ProvisioningApiAppConfigApi
from openapi_client.api.provisioning_api_apps_api import ProvisioningApiAppsApi
from openapi_client.api.provisioning_api_groups_api import ProvisioningApiGroupsApi
from openapi_client.api.provisioning_api_preferences_api import ProvisioningApiPreferencesApi
from openapi_client.api.provisioning_api_users_api import ProvisioningApiUsersApi
from openapi_client.api.settings_log_settings_api import SettingsLogSettingsApi
from openapi_client.api.theming_icon_api import ThemingIconApi
from openapi_client.api.theming_theming_api import ThemingThemingApi
from openapi_client.api.theming_user_theme_api import ThemingUserThemeApi
from openapi_client.api.user_status_heartbeat_api import UserStatusHeartbeatApi
from openapi_client.api.user_status_predefined_status_api import UserStatusPredefinedStatusApi
from openapi_client.api.user_status_statuses_api import UserStatusStatusesApi
from openapi_client.api.user_status_user_status_api import UserStatusUserStatusApi
from openapi_client.api.weather_status_weather_status_api import WeatherStatusWeatherStatusApi

