[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
nextcloud-client-sdk = { path = "../../clients/rust" }
reqwest = "^0.11"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
